make:
	xmllint -schema validation.xsd xsd-xml_1.xml -noout
	xmllint -schema validation.xsd xsd-xml_2.xml -noout
	xmllint -schema validation.xsd xsd-xml_3.xml -noout
	xmllint -schema validation.xsd xsd-xml_4.xml -noout